### ISSUE TITLE
Uzdevumiem ir jāpazūd kad atrodamies kādā no Active vai Completed režīmā

### ISSUE THREAD

**Issue by seleckis** [vguntars/todos#1]
Piemēram esmu Active režīmā, atzīmēju uzdevumu ka pabeigto. Uzdevums vais nav aktīvs. Tad loģiski ka viņam ir jāpazūd. Bet lai lietotājs saprastu kas notika, tad pirmkārt ir jāatzīmē un pēc kādas pussekundes ar animāciju viņš varētu pazūst ar slideUp() vai hide().

**Comment by vguntars** [comment]
Izlabots!
